### PR TITLE
Added max timeout time to get the code

### PR DESCRIPTION
**Pull request by TheGP**
To properly get codes we should be able to break the execution after 5 mins to request new one

### CODE REVIEW

**Comment by Viiprogrammer** [comment]
Looks good. It will be good feature. I will merge and publish today.

May be  you want also add AbortSignal support (for manual aborting),  we can use it for timeout

**Comment by TheGP** [comment]
Maybe in the future, now I need to finish my project so I'm adding only essentials

**Comment by Viiprogrammer** [comment]
Ok, no problem thanks for your work

**Comment by TheGP** [comment]
Thank you for the library!

**Pull request merged**
